/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./../layouts/admin-layout.vue')['default']
    Alert: typeof import('./../components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./../components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./../components/ui/alert/AlertTitle.vue')['default']
    App: typeof import('./../components/App.vue')['default']
    ArticleCard: typeof import('./../components/ArticleCard.vue')['default']
    AuthLayout: typeof import('./../layouts/AuthLayout.vue')['default']
    AuthNavbar: typeof import('./../components/Auth/AuthNavbar.vue')['default']
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    Card: typeof import('./../components/ui/card/Card.vue')['default']
    CardContent: typeof import('./../components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./../components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../components/ui/card/CardTitle.vue')['default']
    DefaultLayout: typeof import('./../layouts/default-layout.vue')['default']
    DefaultNavbar: typeof import('./../components/Default/DefaultNavbar.vue')['default']
    LoginForm: typeof import('./../components/Auth/LoginForm.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    MainNav: typeof import('./../components/Default/MainNav.vue')['default']
    Navbar: typeof import('./../components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./../components/ThemeToggle.vue')['default']
  }
}
