/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./../layouts/AdminLayout.vue')['default']
    AdminNavbar: typeof import('./../components/Admin/AdminNavbar.vue')['default']
    Alert: typeof import('./../components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./../components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./../components/ui/alert/AlertTitle.vue')['default']
    App: typeof import('./../components/App.vue')['default']
    ArticleActions: typeof import('./../components/Articles/ArticleActions.vue')['default']
    ArticleCard: typeof import('./../components/ArticleCard.vue')['default']
    AuthLayout: typeof import('./../layouts/AuthLayout.vue')['default']
    AuthNavbar: typeof import('./../components/Auth/AuthNavbar.vue')['default']
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    Card: typeof import('./../components/ui/card/Card.vue')['default']
    CardContent: typeof import('./../components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./../components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../components/ui/card/CardTitle.vue')['default']
    DefaultLayout: typeof import('./../layouts/DefaultLayout.vue')['default']
    DefaultNavbar: typeof import('./../components/Default/DefaultNavbar.vue')['default']
    Input: typeof import('./../components/ui/input/Input.vue')['default']
    LoginForm: typeof import('./../components/Auth/LoginForm.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    MainNav: typeof import('./../components/Admin/MainNav.vue')['default']
    Navbar: typeof import('./../components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./../components/ui/table/Table.vue')['default']
    TableBody: typeof import('./../components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./../components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./../components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./../components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./../components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./../components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./../components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./../components/ui/table/TableRow.vue')['default']
    ThemeToggle: typeof import('./../components/ThemeToggle.vue')['default']
  }
}
