/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/cms': RouteRecordInfo<'/cms', '/cms', Record<never, never>, Record<never, never>>,
    '/cms/': RouteRecordInfo<'/cms/', '/cms', Record<never, never>, Record<never, never>>,
    '/cms/articles/': RouteRecordInfo<'/cms/articles/', '/cms/articles', Record<never, never>, Record<never, never>>,
    '/cms/articles/create/': RouteRecordInfo<'/cms/articles/create/', '/cms/articles/create', Record<never, never>, Record<never, never>>,
    '/cms/articles/edit/[id]': RouteRecordInfo<'/cms/articles/edit/[id]', '/cms/articles/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cms/companies/': RouteRecordInfo<'/cms/companies/', '/cms/companies', Record<never, never>, Record<never, never>>,
    '/cms/companies/create/': RouteRecordInfo<'/cms/companies/create/', '/cms/companies/create', Record<never, never>, Record<never, never>>,
    '/cms/companies/edit/[id]': RouteRecordInfo<'/cms/companies/edit/[id]', '/cms/companies/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cms/dashboard/': RouteRecordInfo<'/cms/dashboard/', '/cms/dashboard', Record<never, never>, Record<never, never>>,
    '/cms/media/': RouteRecordInfo<'/cms/media/', '/cms/media', Record<never, never>, Record<never, never>>,
    '/cms/users/': RouteRecordInfo<'/cms/users/', '/cms/users', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
